<a href="https://colab.research.google.com/github/Neil-optimus/machine-learning/blob/main/Bagging_boosting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [53]:
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [54]:
df = sns.load_dataset('iris')

In [55]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [56]:
le=LabelEncoder()
df['species']=le.fit_transform(df['species'])

In [57]:
df['species'].value_counts()

species
0    50
1    50
2    50
Name: count, dtype: int64

In [58]:
X = df.drop('species',axis=1)
y = df['species']

In [59]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [60]:
rf_model = RandomForestClassifier(n_estimators=100,
                                  max_depth= None,
                                  random_state=42)

In [61]:
rf_model.fit(X_train,y_train)

RandomForestClassifier(random_state=42)

In [62]:
y_pred = rf_model.predict(X_test)

In [63]:
accuracy_score(y_test,y_pred)

1.0

In [64]:
from sklearn.ensemble import AdaBoostClassifier

In [65]:
model_ada = AdaBoostClassifier(n_estimators=100, random_state=42)

In [66]:
model_ada.fit(X_train,y_train)

AdaBoostClassifier(n_estimators=100, random_state=42)

In [67]:
y_pred_ada = model_ada.predict(X_test)

In [68]:
accuracy_score(y_test,y_pred_ada)

0.9333333333333333

In [69]:
from sklearn.ensemble import GradientBoostingClassifier

In [70]:
model_gd = GradientBoostingClassifier(n_estimators=100,random_state=42)

In [71]:
model_gd.fit(X_train,y_train)

GradientBoostingClassifier(random_state=42)

In [72]:
y_pred_gd = model_gd.predict(X_test)

In [73]:
accuracy_score(y_test,y_pred_gd)

1.0

In [74]:
from xgboost import XGBClassifier

In [75]:
model_xg = XGBClassifier(n_estimators=100,random_state=42,learning_rate=0.1,max_depth=3,use_label_encoder=False,eval_metric='mlogloss',)

In [76]:
model_xg.fit(X_train,y_train)

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [11:45:01] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='mlogloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=3, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=100, n_jobs=None,
              num_parallel_tree=None, ...)

In [80]:
y_pred = model_xg.predict(X_test)

In [81]:
accuracy_score(y_test,y_pred)

1.0