<a href="https://colab.research.google.com/github/Neil-optimus/machine-learning/blob/main/employee_attrition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [74]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [75]:
df = pd.read_csv("employee_attrition_dataset.csv")

In [76]:
df.head()

,Employee_ID,Age,Gender,Marital_Status,Department,Job_Role,Job_Level,Monthly_Income,Hourly_Rate,Years_at_Company,...,Overtime,Project_Count,Average_Hours_Worked_Per_Week,Absenteeism,Work_Environment_Satisfaction,Relationship_with_Manager,Job_Involvement,Distance_From_Home,Number_of_Companies_Worked,Attrition
0,1,58,Female,Married,IT,Manager,1,15488,28,15,...,No,6,54,17,4,4,4,20,3,No
1,2,48,Female,Married,Sales,Assistant,5,13079,28,6,...,Yes,2,45,1,4,1,2,25,2,No
2,3,34,Male,Married,Marketing,Assistant,1,13744,24,24,...,Yes,6,34,2,3,4,4,45,3,No
3,4,27,Female,Divorced,Marketing,Manager,1,6809,26,10,...,No,9,48,18,2,3,1,35,3,No
4,5,40,Male,Divorced,Marketing,Executive,1,10206,52,29,...,No,3,33,0,4,1,3,44,3,No

In [77]:
df.shape

(1000, 26)

In [78]:
df.describe()

,Employee_ID,Age,Job_Level,Monthly_Income,Hourly_Rate,Years_at_Company,Years_in_Current_Role,Years_Since_Last_Promotion,Work_Life_Balance,Job_Satisfaction,Performance_Rating,Training_Hours_Last_Year,Project_Count,Average_Hours_Worked_Per_Week,Absenteeism,Work_Environment_Satisfaction,Relationship_with_Manager,Job_Involvement,Distance_From_Home,Number_of_Companies_Worked
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000,1000.000000,1000.000000,1000.00000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,500.500000,39.991000,3.055000,11499.899000,57.837000,14.922000,7.539000,4.40800,2.495000,3.151000,2.52700,50.043000,4.877000,44.553000,9.524000,2.494000,2.519000,2.503000,24.507000,2.484000
std,288.819436,11.780055,1.399977,4920.529231,24.702037,8.350548,4.001061,2.99508,1.105077,1.426967,1.13073,28.204657,2.546833,8.704192,5.973534,1.110494,1.106736,1.099636,14.138099,1.111296
min,1.000000,20.000000,1.000000,3001.000000,15.000000,1.000000,1.000000,0.00000,1.000000,1.000000,1.00000,0.000000,1.000000,30.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,250.750000,30.000000,2.000000,7395.750000,36.000000,8.000000,4.000000,2.00000,2.000000,2.000000,2.00000,26.000000,3.000000,37.000000,4.000000,2.000000,2.000000,2.000000,12.000000,1.000000
50%,500.500000,41.000000,3.000000,11256.000000,58.000000,15.000000,8.000000,4.00000,3.000000,3.000000,3.00000,50.000000,5.000000,45.000000,9.000000,2.000000,3.000000,3.000000,24.000000,2.000000
75%,750.250000,50.250000,4.000000,15855.000000,80.000000,22.000000,11.000000,7.00000,3.000000,4.000000,4.00000,75.250000,7.000000,52.000000,15.000000,4.000000,4.000000,3.000000,37.000000,3.000000
max,1000.000000,59.000000,5.000000,19999.000000,99.000000,29.000000,14.000000,9.00000,4.000000,5.000000,4.00000,99.000000,9.000000,59.000000,19.000000,4.000000,4.000000,4.000000,49.000000,4.000000

In [79]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 26 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Employee_ID                    1000 non-null   int64
 1   Age                            1000 non-null   int64
 2   Gender                         1000 non-null   object
 3   Marital_Status                 1000 non-null   object
 4   Department                     1000 non-null   object
 5   Job_Role                       1000 non-null   object
 6   Job_Level                      1000 non-null   int64
 7   Monthly_Income                 1000 non-null   int64
 8   Hourly_Rate                    1000 non-null   int64
 9   Years_at_Company               1000 non-null   int64
 10  Years_in_Current_Role          1000 non-null   int64
 11  Years_Since_Last_Promotion     1000 non-null   int64
 12  Work_Life_Balance              1000 non-null   int64
 13  Job_Satisfaction               1000 non-null   int64
 14  Performance_Rating             1000 non-null   int64
 15  Training_Hours_Last_Year       1000 non-null   int64
 16  Overtime                       1000 non-null   object
 17  Project_Count                  1000 non-null   int64
 18  Average_Hours_Worked_Per_Week  1000 non-null   int64
 19  Absenteeism                    1000 non-null   int64
 20  Work_Environment_Satisfaction  1000 non-null   int64
 21  Relationship_with_Manager      1000 non-null   int64
 22  Job_Involvement                1000 non-null   int64
 23  Distance_From_Home             1000 non-null   int64
 24  Number_of_Companies_Worked     1000 non-null   int64
 25  Attrition                      1000 non-null   object
dtypes: int64(20), object(6)
memory usage: 203.3+ KB

In [80]:
df.isnull().sum()

Employee_ID                      0
Age                              0
Gender                           0
Marital_Status                   0
Department                       0
Job_Role                         0
Job_Level                        0
Monthly_Income                   0
Hourly_Rate                      0
Years_at_Company                 0
Years_in_Current_Role            0
Years_Since_Last_Promotion       0
Work_Life_Balance                0
Job_Satisfaction                 0
Performance_Rating               0
Training_Hours_Last_Year         0
Overtime                         0
Project_Count                    0
Average_Hours_Worked_Per_Week    0
Absenteeism                      0
Work_Environment_Satisfaction    0
Relationship_with_Manager        0
Job_Involvement                  0
Distance_From_Home               0
Number_of_Companies_Worked       0
Attrition                        0
dtype: int64

In [81]:
df['Attrition'].value_counts()

Attrition
No     811
Yes    189
Name: count, dtype: int64

In [82]:
df['Attrition'].value_counts(normalize=True)*100

Attrition
No     81.1
Yes    18.9
Name: proportion, dtype: float64

In [83]:
pd.crosstab(df['Overtime'],df['Attrition'],normalize="index")*100

Attrition         No        Yes
Overtime
No         80.468750  19.531250
Yes        81.762295  18.237705

In [84]:
pd.crosstab(df['Job_Satisfaction'],df['Attrition'],normalize='index')*100

Attrition                No        Yes
Job_Satisfaction
1                 80.446927  19.553073
2                 81.767956  18.232044
3                 83.243243  16.756757
4                 81.363636  18.636364
5                 79.148936  20.851064

In [85]:
df = df.drop('Employee_ID',axis=1)

In [86]:
X = df.drop('Attrition',axis=1)
y = df['Attrition']

In [87]:
y.value_counts()

Attrition
No     811
Yes    189
Name: count, dtype: int64

In [88]:
y = y.map({"No":0,"Yes":1})

In [89]:
X.select_dtypes(include="object").columns

Index(['Gender', 'Marital_Status', 'Department', 'Job_Role', 'Overtime'], dtype='object')

In [90]:
X = pd.get_dummies(X,drop_first=True).astype(int)

In [91]:
X

,Age,Job_Level,Monthly_Income,Hourly_Rate,Years_at_Company,Years_in_Current_Role,Years_Since_Last_Promotion,Work_Life_Balance,Job_Satisfaction,Performance_Rating,...,Marital_Status_Married,Marital_Status_Single,Department_HR,Department_IT,Department_Marketing,Department_Sales,Job_Role_Assistant,Job_Role_Executive,Job_Role_Manager,Overtime_Yes
0,58,1,15488,28,15,4,2,1,3,4,...,1,0,0,1,0,0,0,0,1,0
1,48,5,13079,28,6,9,1,2,1,1,...,1,0,0,0,0,1,1,0,0,1
2,34,1,13744,24,24,14,8,3,2,1,...,1,0,0,0,1,0,1,0,0,1
3,27,1,6809,26,10,8,2,3,5,4,...,0,0,0,0,1,0,0,0,1,0
4,40,1,10206,52,29,10,1,2,5,1,...,0,0,0,0,1,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,27,2,4172,76,24,14,3,4,5,4,...,0,0,1,0,0,0,0,0,0,0
996,47,4,11007,71,19,6,0,3,1,1,...,0,1,0,1,0,0,0,0,1,1
997,50,1,4641,43,25,12,3,4,1,1,...,0,0,0,1,0,0,0,1,0,1
998,28,4,19855,92,13,13,0,2,2,2,...,1,0,1,0,0,0,0,1,0,0
999,48,2,11738,39,1,1,4,3,1,2,...,0,0,0,1,0,0,0,0,0,1

In [92]:
from sklearn.preprocessing import StandardScaler

In [93]:
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [94]:
from sklearn.model_selection import train_test_split

In [95]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=
                                                 42,stratify=y)

In [96]:
from sklearn.linear_model import LogisticRegression

In [99]:
model = LogisticRegression(class_weight="balanced",max_iter=1000)

In [100]:
model.fit(X_train,y_train)

LogisticRegression(class_weight='balanced', max_iter=1000)

In [102]:
y_pred = model.predict(X_test)

In [104]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [105]:
accuracy_score(y_test,y_pred)

0.515

In [106]:
confusion_matrix(y_test,y_pred)

array([[91, 71],
       [26, 12]])

In [108]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.78      0.56      0.65       162
           1       0.14      0.32      0.20        38

    accuracy                           0.52       200
   macro avg       0.46      0.44      0.43       200
weighted avg       0.66      0.52      0.57       200

In [109]:
from sklearn.ensemble import RandomForestClassifier

In [110]:
model_rf = RandomForestClassifier(n_estimators=1000,random_state=42,class_weight="balanced")

In [113]:
model_rf.fit(X_train,y_train)

RandomForestClassifier(class_weight='balanced', n_estimators=1000,
                       random_state=42)

In [114]:
y_pred = model_rf.predict(X_test)

In [115]:
accuracy_score(y_test,y_pred)

0.81

In [116]:
confusion_matrix(y_test,y_pred)

array([[162,   0],
       [ 38,   0]])

In [118]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.81      1.00      0.90       162
           1       0.00      0.00      0.00        38

    accuracy                           0.81       200
   macro avg       0.41      0.50      0.45       200
weighted avg       0.66      0.81      0.72       200

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))