<a href="https://colab.research.google.com/github/Neil-optimus/machine-learning/blob/main/GridSearchCV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = sns.load_dataset('iris')

In [3]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
df['species'].value_counts()

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [5]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

In [8]:
X = df.drop('species',axis=1)
y=df['species']

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [10]:
model_knn = KNeighborsClassifier(n_neighbors=9)

In [11]:
model_knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=9)

In [12]:
model_knn.score(X_test,y_test)

1.0

In [13]:
model_svm = SVC(C=30,gamma='auto',kernel='linear')

In [14]:
model_svm.fit(X_train,y_train)

SVC(C=30, gamma='auto', kernel='linear')

In [15]:
model_svm.score(X_test,y_test)

1.0

In [16]:
from sklearn.model_selection import GridSearchCV

In [17]:
Classifier = GridSearchCV(model_svm,param_grid={
    'C':[1,10,20,30],
    'kernel':['linear','rbf'],
},cv = 5,return_train_score=False)

In [18]:
Classifier.fit(X,y)

GridSearchCV(cv=5, estimator=SVC(C=30, gamma='auto', kernel='linear'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['linear', 'rbf']})

In [19]:
Classifier.cv_results_

{'mean_fit_time': array([0.00227723, 0.00241799, 0.0025228 , 0.00252562, 0.00207658,
        0.00244975, 0.00272217, 0.00294652]),
 'std_fit_time': array([1.71737495e-04, 2.24820018e-04, 2.45361081e-04, 2.18104367e-04,
        6.38896668e-05, 5.60467264e-05, 5.16931675e-04, 3.20294810e-04]),
 'mean_score_time': array([0.00175729, 0.00176945, 0.00189571, 0.00186329, 0.00162902,
        0.001827  , 0.00216618, 0.00223112]),
 'std_score_time': array([7.59571210e-05, 1.12543732e-04, 1.01655531e-04, 1.45013808e-04,
        3.03983595e-05, 3.56641044e-05, 6.16238461e-04, 2.61410506e-04]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['linear', 'rbf', 'linear', 'rbf', 'linear', 'rbf',
                    'linear', 'rbf'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'linear'},
  {'C': 1, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'}],
 'split0_test_score': array([0.96666667, 0.96666667, 1.        , 0.96666667, 1.        ,
        0.96666667, 1.        , 0.96666667]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.9       , 0.96666667, 0.9       ,
        0.9       , 0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.93333333,
        0.96666667, 0.9       , 0.93333333]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.97333333, 0.98      , 0.96666667,
        0.96666667, 0.96      , 0.96      ]),
 'std_test_score': array([0.01632993, 0.01632993, 0.03887301, 0.01632993, 0.0421637 ,
        0.03651484, 0.04898979, 0.03887301]),
 'rank_test_score': array([1, 1, 4, 1, 6, 5, 7, 7], dtype=int32)}

In [20]:
df_class1 = pd.DataFrame(Classifier.cv_results_)
df_class1

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002277,0.000172,0.001757,0.000076,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.002418,0.000225,0.001769,0.000113,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.002523,0.000245,0.001896,0.000102,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,4
3,0.002526,0.000218,0.001863,0.000145,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
4,0.002077,0.000064,0.001629,0.000030,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,6
5,0.002450,0.000056,0.001827,0.000036,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,5
6,0.002722,0.000517,0.002166,0.000616,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,7
7,0.002947,0.000320,0.002231,0.000261,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,7

In [21]:
df_class1[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1       linear         0.980000
1        1          rbf         0.980000
2       10       linear         0.973333
3       10          rbf         0.980000
4       20       linear         0.966667
5       20          rbf         0.966667
6       30       linear         0.960000
7       30          rbf         0.960000

In [22]:
Classifier2 = GridSearchCV(model_knn,param_grid={
    'n_neighbors':[3,5,7,9],
    'weights':['uniform','distance'],
    'metric':['euclidean','manhattan''minkowski']
},cv=5,return_train_score=False)

In [23]:
Classifier2.fit(X,y)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(n_neighbors=9),
             param_grid={'metric': ['euclidean', 'manhattanminkowski'],
                         'n_neighbors': [3, 5, 7, 9],
                         'weights': ['uniform', 'distance']})

In [24]:
df_class2 = pd.DataFrame(Classifier2.cv_results_)
df_class2

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_metric,param_n_neighbors,param_weights,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.003129,0.000957,0.004039,0.000573,euclidean,3,uniform,"{'metric': 'euclidean', 'n_neighbors': 3, 'wei...",0.966667,0.966667,0.933333,0.966667,1.0,0.966667,0.021082,6
1,0.002481,0.000365,0.002780,0.000323,euclidean,3,distance,"{'metric': 'euclidean', 'n_neighbors': 3, 'wei...",0.966667,0.966667,0.933333,0.966667,1.0,0.966667,0.021082,6
2,0.001980,0.000340,0.003169,0.000793,euclidean,5,uniform,"{'metric': 'euclidean', 'n_neighbors': 5, 'wei...",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,3
3,0.001729,0.000080,0.002317,0.000755,euclidean,5,distance,"{'metric': 'euclidean', 'n_neighbors': 5, 'wei...",0.966667,1.000000,0.900000,0.966667,1.0,0.966667,0.036515,6
4,0.002419,0.000851,0.003186,0.000371,euclidean,7,uniform,"{'metric': 'euclidean', 'n_neighbors': 7, 'wei...",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
5,0.002307,0.000445,0.002528,0.000425,euclidean,7,distance,"{'metric': 'euclidean', 'n_neighbors': 7, 'wei...",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
6,0.001755,0.000109,0.002498,0.000052,euclidean,9,uniform,"{'metric': 'euclidean', 'n_neighbors': 9, 'wei...",0.966667,1.000000,0.966667,0.933333,1.0,0.973333,0.024944,3
7,0.001654,0.000036,0.001952,0.000077,euclidean,9,distance,"{'metric': 'euclidean', 'n_neighbors': 9, 'wei...",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,3
8,0.000501,0.000025,0.000000,0.000000,manhattanminkowski,3,uniform,"{'metric': 'manhattanminkowski', 'n_neighbors'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
9,0.000496,0.000014,0.000000,0.000000,manhattanminkowski,3,distance,"{'metric': 'manhattanminkowski', 'n_neighbors'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
10,0.000582,0.000100,0.000000,0.000000,manhattanminkowski,5,uniform,"{'metric': 'manhattanminkowski', 'n_neighbors'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
11,0.000657,0.000028,0.000000,0.000000,manhattanminkowski,5,distance,"{'metric': 'manhattanminkowski', 'n_neighbors'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
12,0.000597,0.000050,0.000000,0.000000,manhattanminkowski,7,uniform,"{'metric': 'manhattanminkowski', 'n_neighbors'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
13,0.000782,0.000373,0.000000,0.000000,manhattanminkowski,7,distance,"{'metric': 'manhattanminkowski', 'n_neighbors'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
14,0.000770,0.000246,0.000000,0.000000,manhattanminkowski,9,uniform,"{'metric': 'manhattanminkowski', 'n_neighbors'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
15,0.000501,0.000018,0.000000,0.000000,manhattanminkowski,9,distance,"{'metric': 'manhattanminkowski', 'n_neighbors'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9

In [25]:
df_class2.columns

Index(['mean_fit_time', 'std_fit_time', 'mean_score_time', 'std_score_time',
       'param_metric', 'param_n_neighbors', 'param_weights', 'params',
       'split0_test_score', 'split1_test_score', 'split2_test_score',
       'split3_test_score', 'split4_test_score', 'mean_test_score',
       'std_test_score', 'rank_test_score'],
      dtype='object')

In [26]:
df_class2[['param_metric','param_n_neighbors','param_weights','mean_test_score']].sort_values(by='mean_test_score',ascending=False).head(1)

  param_metric  param_n_neighbors param_weights  mean_test_score
5    euclidean                  7      distance             0.98