<a href="https://colab.research.google.com/github/Neil-optimus/machine-learning/blob/main/RandomSearchCV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [ ]:
df = sns.load_dataset('iris')

In [ ]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
df['species'].value_counts()

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [ ]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

In [ ]:
X = df.drop('species',axis=1)
y=df['species']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [ ]:
model_knn = KNeighborsClassifier(n_neighbors=9)

In [ ]:
model_knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=9)

In [ ]:
model_knn.score(X_test,y_test)

1.0

In [ ]:
model_svm = SVC(C=30,gamma='auto',kernel='linear')

In [ ]:
model_svm.fit(X_train,y_train)

SVC(C=30, gamma='auto', kernel='linear')

In [ ]:
model_svm.score(X_test,y_test)

1.0

In [ ]:
from sklearn.model_selection import RandomizedSearchCV

In [ ]:
rclassifier1 = RandomizedSearchCV((model_svm),{
    'C':[1,10,20,30],
    'kernel':['linear','rbf'],
    'gamma':['auto','scale']
},cv=5,n_iter=10,return_train_score=False)

In [ ]:
rclassifier1.fit(X,y)

RandomizedSearchCV(cv=5, estimator=SVC(C=30, gamma='auto', kernel='linear'),
                   param_distributions={'C': [1, 10, 20, 30],
                                        'gamma': ['auto', 'scale'],
                                        'kernel': ['linear', 'rbf']})

In [ ]:
rclassifier1.cv_results_

{'mean_fit_time': array([0.00308185, 0.00246639, 0.00212979, 0.00240026, 0.00216594,
        0.00213919, 0.00212612, 0.00220437, 0.00207553, 0.00231915]),
 'std_fit_time': array([6.36669099e-04, 1.24705945e-04, 5.11677600e-05, 2.43428176e-04,
        5.11227700e-05, 4.07199390e-05, 9.42669314e-05, 1.08473736e-04,
        6.13190338e-05, 1.36474044e-04]),
 'mean_score_time': array([0.00189943, 0.0018508 , 0.00160007, 0.00183301, 0.00161676,
        0.0016716 , 0.00162058, 0.00162187, 0.00157208, 0.00172305]),
 'std_score_time': array([9.91827479e-05, 1.47876913e-04, 3.35523308e-05, 2.43919914e-04,
        3.53565669e-05, 6.24229562e-05, 9.60264562e-05, 3.06575516e-05,
        4.94793863e-05, 6.99720146e-05]),
 'param_kernel': masked_array(data=['linear', 'linear', 'linear', 'linear', 'rbf', 'rbf',
                    'linear', 'rbf', 'linear', 'rbf'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_gamma': masked_array(data=['scale', 'scale', 'auto', 'auto', 'auto', 'scale',
                    'auto', 'auto', 'auto', 'scale'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_C': masked_array(data=[10, 1, 20, 1, 20, 30, 30, 30, 10, 1],
              mask=[False, False, False, False, False, False, False, False,
                    False, False],
        fill_value=999999),
 'params': [{'kernel': 'linear', 'gamma': 'scale', 'C': 10},
  {'kernel': 'linear', 'gamma': 'scale', 'C': 1},
  {'kernel': 'linear', 'gamma': 'auto', 'C': 20},
  {'kernel': 'linear', 'gamma': 'auto', 'C': 1},
  {'kernel': 'rbf', 'gamma': 'auto', 'C': 20},
  {'kernel': 'rbf', 'gamma': 'scale', 'C': 30},
  {'kernel': 'linear', 'gamma': 'auto', 'C': 30},
  {'kernel': 'rbf', 'gamma': 'auto', 'C': 30},
  {'kernel': 'linear', 'gamma': 'auto', 'C': 10},
  {'kernel': 'rbf', 'gamma': 'scale', 'C': 1}],
 'split0_test_score': array([1.        , 0.96666667, 1.        , 0.96666667, 0.96666667,
        0.96666667, 1.        , 0.96666667, 1.        , 0.96666667]),
 'split1_test_score': array([1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 0.96666667]),
 'split2_test_score': array([0.9       , 0.96666667, 0.9       , 0.96666667, 0.9       ,
        0.93333333, 0.9       , 0.9       , 0.9       , 0.96666667]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 0.96666667,
        0.96666667, 0.9       , 0.93333333, 0.96666667, 0.93333333]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.97333333, 0.98      , 0.96666667, 0.98      , 0.96666667,
        0.97333333, 0.96      , 0.96      , 0.97333333, 0.96666667]),
 'std_test_score': array([0.03887301, 0.01632993, 0.0421637 , 0.01632993, 0.03651484,
        0.02494438, 0.04898979, 0.03887301, 0.03887301, 0.02108185]),
 'rank_test_score': array([3, 1, 7, 1, 6, 3, 9, 9, 3, 7], dtype=int32)}

In [ ]:
r_class1_df = pd.DataFrame(rclassifier1.cv_results_)

In [ ]:
r_class1_df

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_kernel,param_gamma,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.003082,0.000637,0.001899,0.000099,linear,scale,10,"{'kernel': 'linear', 'gamma': 'scale', 'C': 10}",1.000000,1.000000,0.900000,0.966667,1.0,0.973333,0.038873,3
1,0.002466,0.000125,0.001851,0.000148,linear,scale,1,"{'kernel': 'linear', 'gamma': 'scale', 'C': 1}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.002130,0.000051,0.001600,0.000034,linear,auto,20,"{'kernel': 'linear', 'gamma': 'auto', 'C': 20}",1.000000,1.000000,0.900000,0.933333,1.0,0.966667,0.042164,7
3,0.002400,0.000243,0.001833,0.000244,linear,auto,1,"{'kernel': 'linear', 'gamma': 'auto', 'C': 1}",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
4,0.002166,0.000051,0.001617,0.000035,rbf,auto,20,"{'kernel': 'rbf', 'gamma': 'auto', 'C': 20}",0.966667,1.000000,0.900000,0.966667,1.0,0.966667,0.036515,6
5,0.002139,0.000041,0.001672,0.000062,rbf,scale,30,"{'kernel': 'rbf', 'gamma': 'scale', 'C': 30}",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,3
6,0.002126,0.000094,0.001621,0.000096,linear,auto,30,"{'kernel': 'linear', 'gamma': 'auto', 'C': 30}",1.000000,1.000000,0.900000,0.900000,1.0,0.960000,0.048990,9
7,0.002204,0.000108,0.001622,0.000031,rbf,auto,30,"{'kernel': 'rbf', 'gamma': 'auto', 'C': 30}",0.966667,1.000000,0.900000,0.933333,1.0,0.960000,0.038873,9
8,0.002076,0.000061,0.001572,0.000049,linear,auto,10,"{'kernel': 'linear', 'gamma': 'auto', 'C': 10}",1.000000,1.000000,0.900000,0.966667,1.0,0.973333,0.038873,3
9,0.002319,0.000136,0.001723,0.000070,rbf,scale,1,"{'kernel': 'rbf', 'gamma': 'scale', 'C': 1}",0.966667,0.966667,0.966667,0.933333,1.0,0.966667,0.021082,7

In [ ]:
r_class1_df.columns

Index(['mean_fit_time', 'std_fit_time', 'mean_score_time', 'std_score_time',
       'param_kernel', 'param_gamma', 'param_C', 'params', 'split0_test_score',
       'split1_test_score', 'split2_test_score', 'split3_test_score',
       'split4_test_score', 'mean_test_score', 'std_test_score',
       'rank_test_score'],
      dtype='object')

In [ ]:
r_class1_df[['param_kernel','param_gamma','param_C','mean_test_score']].sort_values(by='mean_test_score',ascending=False).head(1)

  param_kernel param_gamma  param_C  mean_test_score
1       linear       scale        1             0.98

In [ ]:
rClassifier2 = RandomizedSearchCV((model_knn),{
    'n_neighbors':[1,3,5,7,9],
    'weights':['uniform','distance'],
    'metric':['euclidean','manhattan','minkowski']
},cv=5,n_iter=10,return_train_score=False)

In [ ]:
rClassifier2.fit(X,y)

RandomizedSearchCV(cv=5, estimator=KNeighborsClassifier(n_neighbors=9),
                   param_distributions={'metric': ['euclidean', 'manhattan',
                                                   'minkowski'],
                                        'n_neighbors': [1, 3, 5, 7, 9],
                                        'weights': ['uniform', 'distance']})

In [ ]:
r_class2 = rClassifier2.cv_results_

In [ ]:
r_class2_df = pd.DataFrame(r_class2)

In [ ]:
r_class2_df

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_weights,param_n_neighbors,param_metric,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002778,0.000380,0.004106,0.000465,uniform,1,manhattan,"{'weights': 'uniform', 'n_neighbors': 1, 'metr...",0.966667,0.966667,0.933333,0.933333,1.0,0.960000,0.024944,7
1,0.002022,0.000048,0.002503,0.000222,distance,3,manhattan,"{'weights': 'distance', 'n_neighbors': 3, 'met...",0.966667,0.966667,0.933333,0.933333,1.0,0.960000,0.024944,7
2,0.002126,0.000251,0.003063,0.000288,uniform,3,minkowski,"{'weights': 'uniform', 'n_neighbors': 3, 'metr...",0.966667,0.966667,0.933333,0.966667,1.0,0.966667,0.021082,4
3,0.001990,0.000111,0.002791,0.000027,uniform,5,minkowski,"{'weights': 'uniform', 'n_neighbors': 5, 'metr...",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,2
4,0.001973,0.000058,0.002362,0.000073,distance,3,euclidean,"{'weights': 'distance', 'n_neighbors': 3, 'met...",0.966667,0.966667,0.933333,0.966667,1.0,0.966667,0.021082,4
5,0.001945,0.000028,0.002989,0.000138,uniform,9,manhattan,"{'weights': 'uniform', 'n_neighbors': 9, 'metr...",0.966667,1.000000,0.966667,0.933333,1.0,0.973333,0.024944,2
6,0.002249,0.000527,0.003623,0.000818,uniform,7,euclidean,"{'weights': 'uniform', 'n_neighbors': 7, 'metr...",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,1
7,0.004195,0.001349,0.006791,0.002379,uniform,1,minkowski,"{'weights': 'uniform', 'n_neighbors': 1, 'metr...",0.966667,0.966667,0.933333,0.933333,1.0,0.960000,0.024944,7
8,0.003509,0.000124,0.005081,0.000699,uniform,3,euclidean,"{'weights': 'uniform', 'n_neighbors': 3, 'metr...",0.966667,0.966667,0.933333,0.966667,1.0,0.966667,0.021082,4
9,0.003368,0.000154,0.004628,0.000210,uniform,3,manhattan,"{'weights': 'uniform', 'n_neighbors': 3, 'metr...",0.966667,0.966667,0.933333,0.933333,1.0,0.960000,0.024944,7

In [ ]:
r_class2_df.columns

Index(['mean_fit_time', 'std_fit_time', 'mean_score_time', 'std_score_time',
       'param_weights', 'param_n_neighbors', 'param_metric', 'params',
       'split0_test_score', 'split1_test_score', 'split2_test_score',
       'split3_test_score', 'split4_test_score', 'mean_test_score',
       'std_test_score', 'rank_test_score'],
      dtype='object')

In [ ]:
r_class2_df[['param_weights','param_n_neighbors','param_metric','mean_test_score']].sort_values(by='mean_test_score',ascending=False).head(1)

  param_weights  param_n_neighbors param_metric  mean_test_score
6       uniform                  7    euclidean             0.98